# Generated by Django 4.0.1 on 2022-03-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20220305_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_registration',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='email',
            field=models.EmailField(default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='files',
            field=models.FileField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
