# Generated by Django 4.0.1 on 2022-03-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_branch_registration_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch_registration',
            old_name='files',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='branch_registration',
            old_name='contact',
            new_name='mobile',
        ),
    ]
