# Generated by Django 4.0.1 on 2022-03-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_rename_files_branch_registration_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch', to='base_app.branch_registration'),
        ),
    ]
